let hardcodedTeams = [
  {
    name: "Kibourne Spring 2024",
    players: [
      {
        id: 0,
        name: "Thomas",
        positions: "1,4,6,5,3,9,7,8,0",
        order: 1,
        rank: 1,
      },
      { id: 1, name: "Vinny", positions: "2,6,4,5,9,7,8,0", order: 3, rank: 1 },
      { id: 2, name: "Greyson", positions: "3,1,5,4,0,9", order: 6, rank: 2 },
      { id: 3, name: "Avett", positions: "1,5,6,2,4,3,9,0", order: 2, rank: 1 },
      {
        id: 4,
        name: "Dakota",
        positions: "3,4,5,0,9,7,1,8",
        order: 4,
        rank: 3,
      },
      {
        id: 5,
        name: "Otto",
        positions: "1,4,3,5,6,9,7,8,0",
        order: 5,
        rank: 2,
      },
      { id: 6, name: "Maverick", positions: "8,7,9,0,4,1", order: 7, rank: 4 },
      { id: 7, name: "Jayce", positions: "7,8,9,0,2", order: 8, rank: 5 },
      { id: 8, name: "Theo", positions: "8,7,9,0,2", order: 9, rank: 5 },
      { id: 9, name: "Owen", positions: "9,7,0,8", order: 10, rank: 7 },
    ],
    games: [
      {
        name: "@ Ashley Votaw",
        innings: [
          {
            label: "1",
            positions: [
              { name: "Pitcher", label: 1, player: undefined },
              { name: "Catcher", label: 2, player: undefined },
              { name: "First base", label: 3, player: undefined },
              { name: "Short stop", label: 6, player: undefined },
              { name: "Third base", label: 5, player: undefined },
              { name: "Second base", label: 4, player: undefined },
              { name: "Center field", label: 8, player: undefined },
              { name: "Left field", label: 7, player: undefined },
              { name: "Right field", label: 9, player: undefined },
              { name: "Out 1", label: 10, player: undefined },
            ],
          },
          {
            label: "2",
            positions: [
              { name: "Pitcher", label: 1, player: undefined },
              { name: "Catcher", label: 2, player: undefined },
              { name: "First base", label: 3, player: undefined },
              { name: "Short stop", label: 6, player: undefined },
              { name: "Third base", label: 5, player: undefined },
              { name: "Second base", label: 4, player: undefined },
              { name: "Center field", label: 8, player: undefined },
              { name: "Left field", label: 7, player: undefined },
              { name: "Right field", label: 9, player: undefined },
              { name: "Out 1", label: 10, player: undefined },
            ],
          },
          {
            label: "3",
            positions: [
              { name: "Pitcher", label: 1, player: undefined },
              { name: "Catcher", label: 2, player: undefined },
              { name: "First base", label: 3, player: undefined },
              { name: "Short stop", label: 6, player: undefined },
              { name: "Third base", label: 5, player: undefined },
              { name: "Second base", label: 4, player: undefined },
              { name: "Center field", label: 8, player: undefined },
              { name: "Left field", label: 7, player: undefined },
              { name: "Right field", label: 9, player: undefined },
              { name: "Out 1", label: 10, player: undefined },
            ],
          },
          {
            label: "4",
            positions: [
              { name: "Pitcher", label: 1, player: undefined },
              { name: "Catcher", label: 2, player: undefined },
              { name: "First base", label: 3, player: undefined },
              { name: "Short stop", label: 6, player: undefined },
              { name: "Third base", label: 5, player: undefined },
              { name: "Second base", label: 4, player: undefined },
              { name: "Center field", label: 8, player: undefined },
              { name: "Left field", label: 7, player: undefined },
              { name: "Right field", label: 9, player: undefined },
              { name: "Out 1", label: 10, player: undefined },
            ],
          },
          {
            label: "5",
            positions: [
              { name: "Pitcher", label: 1, player: undefined },
              { name: "Catcher", label: 2, player: undefined },
              { name: "First base", label: 3, player: undefined },
              { name: "Short stop", label: 6, player: undefined },
              { name: "Third base", label: 5, player: undefined },
              { name: "Second base", label: 4, player: undefined },
              { name: "Center field", label: 8, player: undefined },
              { name: "Left field", label: 7, player: undefined },
              { name: "Right field", label: 9, player: undefined },
              { name: "Out 1", label: 10, player: undefined },
            ],
          },
          {
            label: "6",
            positions: [
              { name: "Pitcher", label: 1, player: undefined },
              { name: "Catcher", label: 2, player: undefined },
              { name: "First base", label: 3, player: undefined },
              { name: "Short stop", label: 6, player: undefined },
              { name: "Third base", label: 5, player: undefined },
              { name: "Second base", label: 4, player: undefined },
              { name: "Center field", label: 8, player: undefined },
              { name: "Left field", label: 7, player: undefined },
              { name: "Right field", label: 9, player: undefined },
              { name: "Out 1", label: 10, player: undefined },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "Kibourne Fall 2024",
    players: [
      { id: 0, name: "Thomas", positions: "1,6,5,4,3,8,0", order: 1, rank: 1 },
      { id: 1, name: "Bo", positions: "2,4,5,6,3,8,0", order: 3, rank: 2 },
      { id: 2, name: "Maverick", positions: "8,7,0,2,9,4", order: 6, rank: 4 },
      { id: 3, name: "Keaton", positions: "7,3,8,4,1,0", order: 2, rank: 3 },
      { id: 4, name: "Eli", positions: "2,4,6,5,8,7,0", order: 4, rank: 2 },
      { id: 5, name: "Owen", positions: "4,6,5,3,0,8,7,9", order: 5, rank: 3 },
      { id: 6, name: "Otto", positions: "3,1,4,5,0", order: 7, rank: 1 },
      { id: 7, name: "Lincoln", positions: "5,1,4,6,0", order: 8, rank: 2 },
      { id: 8, name: "Jordan", positions: "9,0,7,8,4", order: 9, rank: 5 },
      { id: 9, name: "Liam", positions: "7,8,4,0,9", order: 10, rank: 4 },
      { id: 8, name: "Stone", positions: "1,5,6,8,0", order: 9, rank: 1 },
      { id: 8, name: "Joel", positions: "1,6,5,8,0", order: 9, rank: 1 },
    ],
  },
];

function loadTeams() {
  //todo replace with loading from local storage
  return hardcodedTeams;
}
